name: Build xdg-desktop-portal-luminous (nix)

on: [push, pull_request]
jobs:
    build:
        name: "Build xdg-desktop-portal-luminous"
        runs-on: ubuntu-latest
        container:
          image: archlinux:latest
        steps:
            - name: Checkout xdg-desktop-portal-luminous
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: "install deps"
              run: |
                pacman -Syu --noconfirm base-devel clang meson ninja pipewire xkbcommon wayland
            - uses: dtolnay/rust-toolchain@stable
              with:
                components: clippy rustfmt
            - name: Run fmt check
              run: cargo fmt --all -- --check
            - name: Run clippy
              run: cargo clippy -- -D warning
            - name: build target
              run: |
                  meson setup build
                  meson compile -C build
